services:
  web:
    image: proxy-load-balancing:0.1.0
    container_name: proxy-load-balancing-1
    build: ./proxy
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
#      - ./data:/data
      - ./logs:/var/log/nginx/
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
#      - echo "I'm running ${COMPOSE_PROJECT_NAME}"
#    command: [ nginx-debug, '-g', 'daemon off;']
    networks:
      - docker-basic-load-balancing-network


  app1:
    image: service-load-balancing:0.1.0
    container_name: service-load-balancing-1
    build:
      context: ./service
    environment:
      - SERVICE_ID=1
      - PORT=8000
    networks:
      - docker-basic-load-balancing-network

  app2:
    image: service-load-balancing:0.1.0
    container_name: service-load-balancing-2
    build:
      context: ./service
    environment:
      - SERVICE_ID=2
      - PORT=8001
    networks:
      - docker-basic-load-balancing-network

networks:
  docker-basic-load-balancing-network:
    driver: bridge