services:
  web:
    image: api-gateway:0.1.0
    container_name: api-gateway-1
    build: ./etc/nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./etc/nginx/api_backends.conf:/etc/nginx/api_backends.conf
      - ./etc/nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf
      - ./etc/nginx/api_keys.conf:/etc/nginx/api_keys.conf
      - ./etc/nginx/api_conf.d:/etc/nginx/api_conf.d
      - ./logs:/var/log/nginx/
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
#      - echo "I'm running ${COMPOSE_PROJECT_NAME}"
#    command: [ nginx-debug, '-g', 'daemon off;']
    networks:
      - docker-basic-api-gateway-network


  app-inventory-1:
    image: service-inventory:0.1.0
    container_name: service-inventory-1
    build:
      context: ./api
    environment:
      - SERVICE_ID=inventory-1
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-inventory-2:
    image: service-inventory:0.1.0
    container_name: service-inventory-2
    build:
      context: ./api
    environment:
      - SERVICE_ID=inventory-2
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-inventory-3:
    image: service-inventory:0.1.0
    container_name: service-inventory-3
    build:
      context: ./api
    environment:
      - SERVICE_ID=inventory-3
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-pricing-1:
    image: service-pricing:0.1.0
    container_name: service-pricing-1
    build:
      context: ./api
    environment:
      - SERVICE_ID=pricing-1
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-pricing-2:
    image: service-pricing:0.1.0
    container_name: service-pricing-2
    build:
      context: ./api
    environment:
      - SERVICE_ID=pricing-2
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-pricing-3:
    image: service-pricing:0.1.0
    container_name: service-pricing-3
    build:
      context: ./api
    environment:
      - SERVICE_ID=pricing-3
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

networks:
  docker-basic-api-gateway-network:
    driver: bridge