services:
  app-inventory-1:
    image: service-inventory:0.1.0
    container_name: service-inventory-1
    build:
      context: ./api
    environment:
      - SERVICE_ID=inventory-1
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-inventory-2:
    image: service-inventory:0.1.0
    container_name: service-inventory-2
    build:
      context: ./api
    environment:
      - SERVICE_ID=inventory-2
      - PORT=80
    networks:
      - docker-basic-api-gateway-network

  app-inventory-3:
    image: service-inventory:0.1.0
    container_name: service-inventory-3
    build:
      context: ./api
    environment:
      - SERVICE_ID=inventory-3
      - PORT=80
    networks:
      - docker-basic-api-gateway-network